fix(server): add missing header for libc++ after 7d0be514abe7
In file included from server/security_context_v1.cpp:6:
server/security_context_v1_p.h:110:10: error: no template named 'unordered_map' in namespace 'std'
    std::unordered_map<uint32_t, std::unique_ptr<security_context_inviter>> inviters;
    ~~~~~^
server/security_context_v1.cpp:26:5: error: cannot initialize object parameter of type 'Wrapland::Server::Wayland::Global<Wrapland::Server::security_context_manager_v1, 1>' with an expression of type 'Wrapland::Server::security_context_manager_v1::Private'
    create();
    ^~~~~~
server/security_context_v1.cpp:42:39: error: cannot initialize object parameter of type 'Wrapland::Server::Wayland::Global<Wrapland::Server::security_context_manager_v1, 1>' with an expression of type 'Wrapland::Server::security_context_manager_v1::Private'
        listen_fd, close_fd, app_id, *handle->d_ptr->display()->handle, [this, index] {
                                      ^~~~~~~~~~~~~~~
3 errors generated.